# Generated by Django 5.1.7 on 2025-04-22 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
